spring:
  application:
    name: library-management-system

  profiles:
    active: dev   # 개발용 설정 (ddl-auto: create => update, validate)

  output:
    ansi:
      enabled: detect   # 자동 감지하여 컬러 출력

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver #Mysql db 드라이버
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/librarydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 8081

# 파일 저장 경로
file:
  upload-dir: ./uploads




---
#개발 환경 설정
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

#로깅 설정
logging:
  file:
    name: logs/library-system.log   # 로그 파일 저장 설정

  level:
    com.library: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.schema.internal.exec: WARN
    org.hibernate.tool.schema.extract: WARN

---
#운영 환경 설정
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/librarydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}
    # 연결 풀 설정 (HikariCP)
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      # MySQL 연결 재시도 설정
      connection-init-sql: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update    # 로컬 테스트: 테이블 자동 생성/업데이트
    show-sql: false         # 운영환경에서는 SQL 출력 안함
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    # 데이터베이스 초기화 모드
    open-in-view: false

# 파일 업로드 경로 (운영 환경)
file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

# 로깅 설정 (운영 환경)
logging:
  level:
    com.library: INFO
    org.springframework.web: INFO
    org.hibernate: WARN